apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: my-space
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx:latest
    ports:
    - containerPort: 80
#// This is a sample Pod configuration file for a Kubernetes cluster //