apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: myapp-image:latest
    ports:
    - containerPort: 8080
#// This is a sample Pod configuration file for a Kubernetes cluster //   